name: Deploy React App to S3

on:
  push:
    branches:
      - main   # Trigger deployment only on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build  # Run the build command to create a production-ready build

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.0
      with:
        source_dir: './build'    # The directory that contains the React production build
        destination_bucket: ${{ secrets.AWS_S3_BUCKET }}  # Replace with your bucket name or use GitHub Secrets
        destination_dir: '/'      # Set this to the path within your S3 bucket
        acl: public-read         # Set the ACL to public-read if you want the files to be publicly accessible
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}    # Your AWS Access Key
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Your AWS Secret Access Key
        AWS_REGION: ${{ secrets.AWS_REGION }}  # Your AWS Region (e.g., us-east-1)
